apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zmu3nmpld-python 
  janus-idp.io/tekton: zmu3nmpld-python
  backstage.io/kubernetes-id: zmu3nmpld-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zmu3nmpld-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  