apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zmu3nmpld-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zmu3nmpld-python 
  name: zmu3nmpld-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zmu3nmpld-python 
